"""
MicrobiomeDash Configuration
Auto-generated by setup.sh — edit as needed.
"""
import os
from pathlib import Path

# --- Paths ---
PROJECT_DIR = Path("/home/unnot/microbiome-dashboard")
DATA_DIR = PROJECT_DIR / "data"
UPLOAD_DIR = DATA_DIR / "uploads"
DATASET_DIR = DATA_DIR / "datasets"
COMBINED_DIR = DATA_DIR / "combined"
EXPORT_DIR = DATA_DIR / "exports"
PICRUST2_RUNS_DIR = DATA_DIR / "picrust2_runs"
REFERENCE_DIR = DATA_DIR / "references"
R_SCRIPTS_DIR = PROJECT_DIR / "r_scripts"

# --- Database ---
DATABASE_URL = f"sqlite:///{PROJECT_DIR / 'microbiome.db'}"

# --- SILVA 138.1 ---
SILVA_TRAIN_SET = REFERENCE_DIR / "silva_nr99_v138.1_train_set.fa.gz"
SILVA_SPECIES = REFERENCE_DIR / "silva_species_assignment_v138.1.fa.gz"

# --- Conda ---
CONDA_ENV_NAME = "microbiome"
PICRUST2_ENV_NAME = "picrust2"
CONDA_BASE = Path(os.environ.get("CONDA_BASE", "/home/unnot/miniforge3"))


def conda_cmd(args: list[str], env_name: str | None = None) -> list[str]:
    """Wrap a command to run inside a conda environment via conda run."""
    env = env_name or CONDA_ENV_NAME
    return ["conda", "run", "-n", env, "--no-capture-output"] + args

# --- Server ---
HOST = "0.0.0.0"
PORT = 7000 + os.getuid()  # e.g. UID 1000 → port 8000, UID 1001 → 8001, …
DEBUG = True

# --- Pipeline defaults ---
DADA2_DEFAULTS = {
    "trim_left_f": 0,
    "trim_left_r": 0,
    "trunc_len_f": 250,
    "trunc_len_r": 200,
    "min_overlap": 12,
    "threads": min(32, max(1, os.cpu_count() - 1)),  # Cap at 32, leave 1 core free
}
