"""
16S Analyzer Configuration
Auto-generated by setup.sh — edit as needed.
"""
import os
from pathlib import Path

# --- Paths ---
PROJECT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_DIR / "data"
UPLOAD_DIR = DATA_DIR / "uploads"
DATASET_DIR = DATA_DIR / "datasets"
COMBINED_DIR = DATA_DIR / "combined"
EXPORT_DIR = DATA_DIR / "exports"
PICRUST2_RUNS_DIR = DATA_DIR / "picrust2_runs"
REFERENCE_DIR = DATA_DIR / "references"
R_SCRIPTS_DIR = PROJECT_DIR / "r_scripts"

# --- Database ---
DATABASE_URL = f"sqlite:///{PROJECT_DIR / 'microbiome.db'}"

# --- SILVA 138.1 ---
SILVA_TRAIN_SET = REFERENCE_DIR / "silva_nr99_v138.1_train_set.fa.gz"
SILVA_SPECIES = REFERENCE_DIR / "silva_species_assignment_v138.1.fa.gz"

# --- Conda ---
CONDA_ENV_NAME = "microbiome_16S"
DADA2_ENV_NAME = "dada2_16S"
ANALYSIS_ENV_NAME = "analysis_16S"
PICRUST2_ENV_NAME = "picrust2_16S"
CONDA_BASE = Path(os.environ.get("CONDA_BASE", Path.home() / "miniforge3"))

# Map R script filenames to the conda env that has their dependencies.
_R_SCRIPT_ENV_MAP = {
    "run_dada2.R": DADA2_ENV_NAME,
    "run_taxonomy.R": DADA2_ENV_NAME,
    "run_ancombc.R": ANALYSIS_ENV_NAME,
    "run_deseq2.R": ANALYSIS_ENV_NAME,
    "run_aldex2.R": ANALYSIS_ENV_NAME,
    "run_linda.R": ANALYSIS_ENV_NAME,
    "run_maaslin2.R": ANALYSIS_ENV_NAME,
    "run_nmds.R": ANALYSIS_ENV_NAME,
}


def r_script_env(script_name: str) -> str:
    """Return the conda env name for a given R script filename."""
    return _R_SCRIPT_ENV_MAP.get(script_name, CONDA_ENV_NAME)


def conda_cmd(args: list[str], env_name: str | None = None) -> list[str]:
    """Wrap a command to run inside a conda environment via conda run."""
    env = env_name or CONDA_ENV_NAME
    return ["conda", "run", "-n", env, "--no-capture-output"] + args

# --- Server ---
HOST = "0.0.0.0"
PORT = 7000 + os.getuid()  # e.g. UID 1000 → port 8000, UID 1001 → 8001, …
DEBUG = True

# --- Pipeline defaults ---
DADA2_DEFAULTS = {
    "trim_left_f": 0,
    "trim_left_r": 0,
    "trunc_len_f": 0,
    "trunc_len_r": 0,
    "min_overlap": 12,
    "threads": min(32, max(1, os.cpu_count() - 1)),  # Cap at 32, leave 1 core free
}
